spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prompthub
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8080